// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1746808073);
user_pref("browser.search.region", "CA");
user_pref("calendar.caldav.googleResync", 1746808072);
user_pref("calendar.list.sortOrder", "acc95469-da28-4e45-90b7-977b601f37ab");
user_pref("calendar.registry.acc95469-da28-4e45-90b7-977b601f37ab.calendar-main-default", true);
user_pref("calendar.registry.acc95469-da28-4e45-90b7-977b601f37ab.calendar-main-in-composite", true);
user_pref("calendar.registry.acc95469-da28-4e45-90b7-977b601f37ab.disabled", true);
user_pref("calendar.registry.acc95469-da28-4e45-90b7-977b601f37ab.name", "Home");
user_pref("calendar.registry.acc95469-da28-4e45-90b7-977b601f37ab.type", "storage");
user_pref("calendar.registry.acc95469-da28-4e45-90b7-977b601f37ab.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "America/Moncton");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1746808072);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20241211204238");
user_pref("extensions.lastAppVersion", "115.18.0");
user_pref("extensions.lastPlatformVersion", "115.18.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"699b87ac-7013-4e9d-8d43-b9d35c74d015\",\"google@search.mozilla.org\":\"a298fa47-83a8-405c-9731-d1214a0e5be4\",\"ddg@search.mozilla.org\":\"188ed6f5-9095-420d-9c4f-69d27f94ba81\",\"amazon@search.mozilla.org\":\"8c480264-7592-45b1-8b2a-1c7bf4827776\",\"wikipedia@search.mozilla.org\":\"3cfb1d8f-e77d-4ca0-bb5e-4144e20b7591\",\"bing@search.mozilla.org\":\"5a8456d4-19e1-4826-ab8f-ba2125e33b9f\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "752fd3b8-ff95-4b73-9a4d-0ee28d68c2a");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.18.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1746808070);
user_pref("toolkit.telemetry.cachedClientID", "fb97b079-e56d-4b39-9014-c732720f0378");
user_pref("toolkit.telemetry.previousBuildID", "20241211204238");
